### ISSUE TITLE
bucket evaluation not working

### ISSUE THREAD

**Issue by akobler** [asafdav/ng-s3upload#50]
First thanks for providing this cool piece of software! 

I encounter the following problem:
If I print the value of bucket (assigned at line 40 in https://github.com/asafdav/ng-s3upload/blob/v0.1.2/src/ng-s3upload/directives/s3-upload.js) to the console, it is -1. After changing 

var bucket = scope.$eval(attrs.bucket);
to 
var bucket = attrs.bucket;

the HTML template looks like:

`<div id="uploader" s3-upload bucket="{{env.s3Bucket}}" ng-model="files.first" s3-upload-options="{{s3options}}" do-upload="performUpload"></div>`

whereby env holds some environment variables.

I get the right value. Is it a bug? Thanks for any hints/suggestions.

Versions:
- AngularJS: v1.2.1
- ng-s3upload: v0.1.2
- Chromium: Version 39.0.2171.71 Built on 8.0, running on Debian 8.0 (64-bit)

**Comment by asafdav** [comment]
You shouldn't change anything, you don't need to use curly braces for the bucket attribute and it will work for you.

**Comment by akobler** [comment]
I see, it works perfectly without the curly braces. Thank you!

**Comment by asafdav** [comment]
You're welcome
